version: 2.1

orbs:
  codacy: codacy/base@12.1.5

workflows:
  version: 2
  test-and-publish:
    jobs:
      - codacy/checkout_and_version
      - codacy/shell:
          name: build_and_scan_docker
          context: CodacyDocker
          requires:
            - codacy/checkout_and_version
          cmd: make docker_build && make docker_scan
          filters:
            branches:
              ignore:
                - master
      - codacy/shell:
          name: build_and_publish_docker
          context: CodacyDocker
          requires:
            - codacy/checkout_and_version
          cmd: |
            make docker_build && \
              make docker_scan && \
              make push-docker-image && \
              make push-latest-docker-image
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          context: CodacyAWS
          requires:
            - build_and_publish_docker
          filters:
            branches:
              only:
                - master
